# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCalendarWidget, QDateEdit, QDateTimeEdit,
    QFrame, QGroupBox, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QPushButton, QRadioButton,
    QSizePolicy, QSplitter, QStatusBar, QTabWidget,
    QTableWidget, QTableWidgetItem, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1537, 773)
        MainWindow.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(11, 10, 1311, 531))
        font = QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setIconSize(QSize(20, 20))
        self.tabWidget.setElideMode(Qt.ElideMiddle)
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.label = QLabel(self.tab_1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 640, 480))
        self.label.setMinimumSize(QSize(640, 480))
        self.label.setMaximumSize(QSize(640, 480))
        self.label.setStyleSheet(u"background-color: rgb(109, 109, 109);")
        self.label_2 = QLabel(self.tab_1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(655, 10, 640, 480))
        self.label_2.setMinimumSize(QSize(640, 480))
        self.label_2.setMaximumSize(QSize(640, 480))
        self.label_2.setStyleSheet(u"background-color: rgb(109, 109, 109);")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tableWidget = QTableWidget(self.tab_2)
        if (self.tableWidget.columnCount() < 7):
            self.tableWidget.setColumnCount(7)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        if (self.tableWidget.rowCount() < 12):
            self.tableWidget.setRowCount(12)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidget.setItem(0, 0, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.tableWidget.setItem(0, 3, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.tableWidget.setItem(0, 4, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        __qtablewidgetitem22.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEditable|Qt.ItemIsDragEnabled|Qt.ItemIsDropEnabled|Qt.ItemIsUserCheckable);
        self.tableWidget.setItem(3, 0, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        __qtablewidgetitem23.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEditable|Qt.ItemIsDragEnabled|Qt.ItemIsDropEnabled|Qt.ItemIsUserCheckable);
        self.tableWidget.setItem(3, 3, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        __qtablewidgetitem24.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEditable|Qt.ItemIsDragEnabled|Qt.ItemIsDropEnabled|Qt.ItemIsUserCheckable);
        self.tableWidget.setItem(3, 4, __qtablewidgetitem24)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 10, 881, 481))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.calendarWidget = QCalendarWidget(self.tab_2)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(900, 10, 401, 241))
        self.calendarWidget.setStyleSheet(u"font: 8pt \"MS Shell Dlg 2\";")
        self.groupBox_6 = QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(900, 260, 401, 171))
        self.groupBox_6.setFont(font)
        self.splitter_2 = QSplitter(self.groupBox_6)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(10, 80, 381, 22))
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.label_11 = QLabel(self.splitter_2)
        self.label_11.setObjectName(u"label_11")
        self.splitter_2.addWidget(self.label_11)
        self.dateEdit_2 = QDateEdit(self.splitter_2)
        self.dateEdit_2.setObjectName(u"dateEdit_2")
        self.splitter_2.addWidget(self.dateEdit_2)
        self.btn_find = QPushButton(self.groupBox_6)
        self.btn_find.setObjectName(u"btn_find")
        self.btn_find.setGeometry(QRect(170, 120, 221, 41))
        self.splitter = QSplitter(self.groupBox_6)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(10, 40, 381, 22))
        self.splitter.setOrientation(Qt.Horizontal)
        self.label_9 = QLabel(self.splitter)
        self.label_9.setObjectName(u"label_9")
        self.splitter.addWidget(self.label_9)
        self.dateEdit = QDateEdit(self.splitter)
        self.dateEdit.setObjectName(u"dateEdit")
        self.splitter.addWidget(self.dateEdit)
        self.btn_export = QPushButton(self.tab_2)
        self.btn_export.setObjectName(u"btn_export")
        self.btn_export.setGeometry(QRect(900, 440, 401, 51))
        self.btn_export.setFont(font)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.slot_frame = QFrame(self.tab_3)
        self.slot_frame.setObjectName(u"slot_frame")
        self.slot_frame.setGeometry(QRect(10, 10, 911, 481))
        self.slot_frame.setFrameShape(QFrame.StyledPanel)
        self.slot_frame.setFrameShadow(QFrame.Raised)
        self.slot_0 = QPushButton(self.slot_frame)
        self.slot_0.setObjectName(u"slot_0")
        self.slot_0.setGeometry(QRect(10, 20, 140, 210))
        self.slot_1 = QPushButton(self.slot_frame)
        self.slot_1.setObjectName(u"slot_1")
        self.slot_1.setGeometry(QRect(160, 20, 140, 210))
        self.slot_2 = QPushButton(self.slot_frame)
        self.slot_2.setObjectName(u"slot_2")
        self.slot_2.setGeometry(QRect(310, 20, 140, 210))
        self.slot_3 = QPushButton(self.slot_frame)
        self.slot_3.setObjectName(u"slot_3")
        self.slot_3.setGeometry(QRect(460, 20, 140, 210))
        self.slot_4 = QPushButton(self.slot_frame)
        self.slot_4.setObjectName(u"slot_4")
        self.slot_4.setGeometry(QRect(610, 20, 140, 210))
        self.slot_6 = QPushButton(self.slot_frame)
        self.slot_6.setObjectName(u"slot_6")
        self.slot_6.setGeometry(QRect(10, 260, 140, 210))
        self.slot_8 = QPushButton(self.slot_frame)
        self.slot_8.setObjectName(u"slot_8")
        self.slot_8.setGeometry(QRect(310, 260, 140, 210))
        self.slot_9 = QPushButton(self.slot_frame)
        self.slot_9.setObjectName(u"slot_9")
        self.slot_9.setGeometry(QRect(460, 260, 140, 210))
        self.slot_7 = QPushButton(self.slot_frame)
        self.slot_7.setObjectName(u"slot_7")
        self.slot_7.setGeometry(QRect(160, 260, 141, 210))
        self.slot_10 = QPushButton(self.slot_frame)
        self.slot_10.setObjectName(u"slot_10")
        self.slot_10.setGeometry(QRect(610, 260, 140, 210))
        self.slot_11 = QPushButton(self.slot_frame)
        self.slot_11.setObjectName(u"slot_11")
        self.slot_11.setGeometry(QRect(760, 260, 140, 210))
        self.slot_5 = QPushButton(self.slot_frame)
        self.slot_5.setObjectName(u"slot_5")
        self.slot_5.setGeometry(QRect(760, 20, 140, 210))
        self.groupBox = QGroupBox(self.tab_3)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(930, 30, 361, 251))
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 30, 121, 211))
        self.layoutWidget1 = QWidget(self.groupBox_2)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(10, 30, 105, 171))
        self.verticalLayout = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.all_opt = QRadioButton(self.layoutWidget1)
        self.all_opt.setObjectName(u"all_opt")

        self.verticalLayout.addWidget(self.all_opt)

        self.available_opt = QRadioButton(self.layoutWidget1)
        self.available_opt.setObjectName(u"available_opt")

        self.verticalLayout.addWidget(self.available_opt)

        self.resersed_opt = QRadioButton(self.layoutWidget1)
        self.resersed_opt.setObjectName(u"resersed_opt")

        self.verticalLayout.addWidget(self.resersed_opt)

        self.unavailable_opt = QRadioButton(self.layoutWidget1)
        self.unavailable_opt.setObjectName(u"unavailable_opt")

        self.verticalLayout.addWidget(self.unavailable_opt)

        self.groupBox_3 = QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(140, 30, 141, 211))
        self.layoutWidget2 = QWidget(self.groupBox_3)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(10, 30, 121, 171))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.layoutWidget2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setStyleSheet(u"background-color: rgb(131, 131, 131);")

        self.verticalLayout_2.addWidget(self.label_3)

        self.label_4 = QLabel(self.layoutWidget2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setStyleSheet(u"background-color: rgb(0, 170, 0);")

        self.verticalLayout_2.addWidget(self.label_4)

        self.label_5 = QLabel(self.layoutWidget2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setStyleSheet(u"background-color: rgb(212, 212, 0);")

        self.verticalLayout_2.addWidget(self.label_5)

        self.label_6 = QLabel(self.layoutWidget2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setStyleSheet(u"background-color: rgb(195, 0, 0);")

        self.verticalLayout_2.addWidget(self.label_6)

        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(290, 30, 61, 211))
        self.layoutWidget3 = QWidget(self.groupBox_4)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(10, 30, 41, 171))
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.all_slot = QLabel(self.layoutWidget3)
        self.all_slot.setObjectName(u"all_slot")

        self.verticalLayout_3.addWidget(self.all_slot)

        self.available_slot = QLabel(self.layoutWidget3)
        self.available_slot.setObjectName(u"available_slot")

        self.verticalLayout_3.addWidget(self.available_slot)

        self.reserved_slot = QLabel(self.layoutWidget3)
        self.reserved_slot.setObjectName(u"reserved_slot")

        self.verticalLayout_3.addWidget(self.reserved_slot)

        self.unavailable_slot = QLabel(self.layoutWidget3)
        self.unavailable_slot.setObjectName(u"unavailable_slot")

        self.verticalLayout_3.addWidget(self.unavailable_slot)

        self.groupBox_5 = QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(930, 290, 361, 141))
        self.layoutWidget4 = QWidget(self.groupBox_5)
        self.layoutWidget4.setObjectName(u"layoutWidget4")
        self.layoutWidget4.setGeometry(QRect(10, 30, 135, 101))
        self.verticalLayout_4 = QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.layoutWidget4)
        self.label_7.setObjectName(u"label_7")

        self.verticalLayout_4.addWidget(self.label_7)

        self.label_10 = QLabel(self.layoutWidget4)
        self.label_10.setObjectName(u"label_10")

        self.verticalLayout_4.addWidget(self.label_10)

        self.label_8 = QLabel(self.layoutWidget4)
        self.label_8.setObjectName(u"label_8")

        self.verticalLayout_4.addWidget(self.label_8)

        self.layoutWidget5 = QWidget(self.groupBox_5)
        self.layoutWidget5.setObjectName(u"layoutWidget5")
        self.layoutWidget5.setGeometry(QRect(160, 30, 191, 101))
        self.verticalLayout_5 = QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.lincense_edit = QLineEdit(self.layoutWidget5)
        self.lincense_edit.setObjectName(u"lincense_edit")

        self.verticalLayout_5.addWidget(self.lincense_edit)

        self.type_edit = QLineEdit(self.layoutWidget5)
        self.type_edit.setObjectName(u"type_edit")

        self.verticalLayout_5.addWidget(self.type_edit)

        self.entry_edit = QLineEdit(self.layoutWidget5)
        self.entry_edit.setObjectName(u"entry_edit")

        self.verticalLayout_5.addWidget(self.entry_edit)

        self.tabWidget.addTab(self.tab_3, "")
        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(1330, 20, 191, 361))
        self.groupBox_7.setFont(font)
        self.label_12 = QLabel(self.groupBox_7)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 30, 171, 121))
        self.label_12.setStyleSheet(u"background-color: rgb(109, 109, 109);")
        self.label_13 = QLabel(self.groupBox_7)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 160, 171, 121))
        self.label_13.setStyleSheet(u"background-color: rgb(109, 109, 109);")
        self.lineEdit = QLineEdit(self.groupBox_7)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 290, 171, 61))
        self.groupBox_8 = QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(1330, 380, 191, 361))
        self.groupBox_8.setFont(font)
        self.label_14 = QLabel(self.groupBox_8)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 30, 171, 121))
        self.label_14.setStyleSheet(u"background-color: rgb(109, 109, 109);")
        self.label_15 = QLabel(self.groupBox_8)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 160, 171, 121))
        self.label_15.setStyleSheet(u"background-color: rgb(109, 109, 109);")
        self.lineEdit_2 = QLineEdit(self.groupBox_8)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(10, 290, 171, 61))
        self.groupBox_9 = QGroupBox(self.centralwidget)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(200, 550, 391, 91))
        self.groupBox_9.setFont(font)
        self.dateTimeEdit = QDateTimeEdit(self.groupBox_9)
        self.dateTimeEdit.setObjectName(u"dateTimeEdit")
        self.dateTimeEdit.setGeometry(QRect(10, 30, 371, 41))
        self.groupBox_10 = QGroupBox(self.centralwidget)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(10, 550, 181, 151))
        self.groupBox_10.setFont(font)
        self.pushButton = QPushButton(self.groupBox_10)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 30, 161, 51))
        self.pushButton_2 = QPushButton(self.groupBox_10)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(10, 90, 161, 51))
        self.groupBox_11 = QGroupBox(self.centralwidget)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(200, 650, 391, 51))
        self.groupBox_11.setFont(font)
        self.radioButton = QRadioButton(self.groupBox_11)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(140, 20, 101, 21))
        self.radioButton_2 = QRadioButton(self.groupBox_11)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(260, 20, 121, 21))
        self.label_16 = QLabel(self.groupBox_11)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 20, 121, 21))
        self.label_16.setStyleSheet(u"background-color: rgb(0, 170, 0);")
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(990, 710, 341, 20))
        font1 = QFont()
        font1.setFamilies([u"MS Shell Dlg 2"])
        font1.setPointSize(8)
        font1.setBold(False)
        font1.setItalic(False)
        self.label_18.setFont(font1)
        self.label_18.setStyleSheet(u"font: 8pt \"MS Shell Dlg 2\";")
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(1130, 550, 191, 71))
        self.pushButton_3.setFont(font)
        self.groupBox_12 = QGroupBox(self.centralwidget)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(600, 550, 331, 151))
        self.groupBox_12.setFont(font)
        self.layoutWidget4_2 = QWidget(self.groupBox_12)
        self.layoutWidget4_2.setObjectName(u"layoutWidget4_2")
        self.layoutWidget4_2.setGeometry(QRect(10, 30, 135, 101))
        self.verticalLayout_6 = QVBoxLayout(self.layoutWidget4_2)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_17 = QLabel(self.layoutWidget4_2)
        self.label_17.setObjectName(u"label_17")

        self.verticalLayout_6.addWidget(self.label_17)

        self.label_19 = QLabel(self.layoutWidget4_2)
        self.label_19.setObjectName(u"label_19")

        self.verticalLayout_6.addWidget(self.label_19)

        self.label_20 = QLabel(self.layoutWidget4_2)
        self.label_20.setObjectName(u"label_20")

        self.verticalLayout_6.addWidget(self.label_20)

        self.layoutWidget5_2 = QWidget(self.groupBox_12)
        self.layoutWidget5_2.setObjectName(u"layoutWidget5_2")
        self.layoutWidget5_2.setGeometry(QRect(160, 30, 161, 101))
        self.verticalLayout_7 = QVBoxLayout(self.layoutWidget5_2)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.lincense_edit_2 = QLineEdit(self.layoutWidget5_2)
        self.lincense_edit_2.setObjectName(u"lincense_edit_2")

        self.verticalLayout_7.addWidget(self.lincense_edit_2)

        self.type_edit_2 = QLineEdit(self.layoutWidget5_2)
        self.type_edit_2.setObjectName(u"type_edit_2")

        self.verticalLayout_7.addWidget(self.type_edit_2)

        self.entry_edit_2 = QLineEdit(self.layoutWidget5_2)
        self.entry_edit_2.setObjectName(u"entry_edit_2")

        self.verticalLayout_7.addWidget(self.entry_edit_2)

        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(940, 550, 181, 71))
        self.pushButton_4.setFont(font)
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(940, 630, 381, 71))
        self.pushButton_5.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setSizeGripEnabled(True)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.label_2.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"Entry Camera view", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"License Number", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Name", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Email", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Phone", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Slot", None));
        ___qtablewidgetitem5 = self.tableWidget.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Check-in", None));
        ___qtablewidgetitem6 = self.tableWidget.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Checkout", None));
        ___qtablewidgetitem7 = self.tableWidget.verticalHeaderItem(0)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"1", None));
        ___qtablewidgetitem8 = self.tableWidget.verticalHeaderItem(1)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"1", None));
        ___qtablewidgetitem9 = self.tableWidget.verticalHeaderItem(2)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"2", None));
        ___qtablewidgetitem10 = self.tableWidget.verticalHeaderItem(3)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"3", None));
        ___qtablewidgetitem11 = self.tableWidget.verticalHeaderItem(4)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"4", None));
        ___qtablewidgetitem12 = self.tableWidget.verticalHeaderItem(5)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"5", None));
        ___qtablewidgetitem13 = self.tableWidget.verticalHeaderItem(6)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"6", None));
        ___qtablewidgetitem14 = self.tableWidget.verticalHeaderItem(7)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"7", None));
        ___qtablewidgetitem15 = self.tableWidget.verticalHeaderItem(8)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"8", None));
        ___qtablewidgetitem16 = self.tableWidget.verticalHeaderItem(9)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"10", None));
        ___qtablewidgetitem17 = self.tableWidget.verticalHeaderItem(10)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"11", None));
        ___qtablewidgetitem18 = self.tableWidget.verticalHeaderItem(11)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"12", None));

        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)

        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Information Filter:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"To:", None))
        self.btn_find.setText(QCoreApplication.translate("MainWindow", u"Find", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"From:", None))
        self.btn_export.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u" Database View", None))
        self.slot_0.setText(QCoreApplication.translate("MainWindow", u"SA-00", None))
        self.slot_1.setText(QCoreApplication.translate("MainWindow", u"SA-01", None))
        self.slot_2.setText(QCoreApplication.translate("MainWindow", u"SA-02", None))
        self.slot_3.setText(QCoreApplication.translate("MainWindow", u"SA-03", None))
        self.slot_4.setText(QCoreApplication.translate("MainWindow", u"SA-04", None))
        self.slot_6.setText(QCoreApplication.translate("MainWindow", u"SA-06", None))
        self.slot_8.setText(QCoreApplication.translate("MainWindow", u"SA-08", None))
        self.slot_9.setText(QCoreApplication.translate("MainWindow", u"SA-09", None))
        self.slot_7.setText(QCoreApplication.translate("MainWindow", u"SA-07", None))
        self.slot_10.setText(QCoreApplication.translate("MainWindow", u"SA-10", None))
        self.slot_11.setText(QCoreApplication.translate("MainWindow", u"SA-11", None))
        self.slot_5.setText(QCoreApplication.translate("MainWindow", u"SA-05", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Status indiacation:", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"filters", None))
        self.all_opt.setText(QCoreApplication.translate("MainWindow", u"All", None))
        self.available_opt.setText(QCoreApplication.translate("MainWindow", u"Available", None))
        self.resersed_opt.setText(QCoreApplication.translate("MainWindow", u"Reserved", None))
        self.unavailable_opt.setText(QCoreApplication.translate("MainWindow", u"Unvailable", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Color indicator", None))
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_6.setText("")
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Total:", None))
        self.all_slot.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.available_slot.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.reserved_slot.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.unavailable_slot.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Information:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Lincense Number:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Type:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Entry Time: ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Parking Slot View", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Entrance Capture", None))
        self.label_12.setText("")
        self.label_13.setText("")
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Exit  Capture", None))
        self.label_14.setText("")
        self.label_15.setText("")
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Runtime:", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Toolboxs:", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Connection", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Send SMS/Email", None))
        self.groupBox_11.setTitle("")
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"Accepted", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"Unaccpeted", None))
        self.label_16.setText("")
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Created by: University of Technology and Education Team", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Login", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"Information", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Total Slot:", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Available Slot:", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Total Car:", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Go to Website", None))
    # retranslateUi

