# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCalendarWidget, QComboBox, QDateEdit,
    QFormLayout, QFrame, QGroupBox, QHBoxLayout,
    QHeaderView, QLCDNumber, QLabel, QLineEdit,
    QMainWindow, QPushButton, QRadioButton, QSizePolicy,
    QTabWidget, QTableWidget, QTableWidgetItem, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1395, 704)
        MainWindow.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(11, 10, 1031, 531))
        font = QFont()
        font.setFamilies([u"MS Shell Dlg 2"])
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setIconSize(QSize(20, 20))
        self.tabWidget.setElideMode(Qt.ElideMiddle)
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.entrance_view = QLabel(self.tab_1)
        self.entrance_view.setObjectName(u"entrance_view")
        self.entrance_view.setGeometry(QRect(10, 10, 500, 480))
        self.entrance_view.setMinimumSize(QSize(320, 180))
        self.entrance_view.setMaximumSize(QSize(640, 480))
        self.entrance_view.setStyleSheet(u"background-color: rgb(109, 109, 109);")
        self.exit_view = QLabel(self.tab_1)
        self.exit_view.setObjectName(u"exit_view")
        self.exit_view.setGeometry(QRect(520, 10, 500, 480))
        self.exit_view.setMinimumSize(QSize(500, 400))
        self.exit_view.setMaximumSize(QSize(640, 480))
        self.exit_view.setStyleSheet(u"background-color: rgb(109, 109, 109);")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tableWidget = QTableWidget(self.tab_2)
        if (self.tableWidget.columnCount() < 5):
            self.tableWidget.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        if (self.tableWidget.rowCount() < 15):
            self.tableWidget.setRowCount(15)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.tableWidget.setItem(0, 0, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.tableWidget.setItem(0, 2, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.tableWidget.setItem(0, 3, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        __qtablewidgetitem23.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEditable|Qt.ItemIsDragEnabled|Qt.ItemIsDropEnabled|Qt.ItemIsUserCheckable);
        self.tableWidget.setItem(3, 0, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        __qtablewidgetitem24.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEditable|Qt.ItemIsDragEnabled|Qt.ItemIsDropEnabled|Qt.ItemIsUserCheckable);
        self.tableWidget.setItem(3, 2, __qtablewidgetitem24)
        __qtablewidgetitem25 = QTableWidgetItem()
        __qtablewidgetitem25.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEditable|Qt.ItemIsDragEnabled|Qt.ItemIsDropEnabled|Qt.ItemIsUserCheckable);
        self.tableWidget.setItem(3, 3, __qtablewidgetitem25)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 10, 691, 481))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.calendarWidget = QCalendarWidget(self.tab_2)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(710, 10, 311, 281))
        self.calendarWidget.setStyleSheet(u"font: 8pt \"MS Shell Dlg 2\";")
        self.groupBox_6 = QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(710, 300, 311, 141))
        self.groupBox_6.setFont(font)
        self.btn_find = QPushButton(self.groupBox_6)
        self.btn_find.setObjectName(u"btn_find")
        self.btn_find.setGeometry(QRect(160, 90, 141, 41))
        self.layoutWidget = QWidget(self.groupBox_6)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 30, 291, 51))
        self.formLayout_2 = QFormLayout(self.layoutWidget)
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_9 = QLabel(self.layoutWidget)
        self.label_9.setObjectName(u"label_9")

        self.formLayout_2.setWidget(0, QFormLayout.LabelRole, self.label_9)

        self.dateEdit = QDateEdit(self.layoutWidget)
        self.dateEdit.setObjectName(u"dateEdit")

        self.formLayout_2.setWidget(0, QFormLayout.FieldRole, self.dateEdit)

        self.label_11 = QLabel(self.layoutWidget)
        self.label_11.setObjectName(u"label_11")

        self.formLayout_2.setWidget(1, QFormLayout.LabelRole, self.label_11)

        self.dateEdit_2 = QDateEdit(self.layoutWidget)
        self.dateEdit_2.setObjectName(u"dateEdit_2")

        self.formLayout_2.setWidget(1, QFormLayout.FieldRole, self.dateEdit_2)

        self.btn_reset = QPushButton(self.groupBox_6)
        self.btn_reset.setObjectName(u"btn_reset")
        self.btn_reset.setGeometry(QRect(10, 90, 141, 41))
        self.btn_export = QPushButton(self.tab_2)
        self.btn_export.setObjectName(u"btn_export")
        self.btn_export.setGeometry(QRect(710, 450, 311, 41))
        self.btn_export.setFont(font)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.slot_frame = QFrame(self.tab_3)
        self.slot_frame.setObjectName(u"slot_frame")
        self.slot_frame.setGeometry(QRect(10, 10, 731, 481))
        self.slot_frame.setFrameShape(QFrame.StyledPanel)
        self.slot_frame.setFrameShadow(QFrame.Raised)
        self.slot_0 = QPushButton(self.slot_frame)
        self.slot_0.setObjectName(u"slot_0")
        self.slot_0.setGeometry(QRect(10, 20, 115, 210))
        self.slot_1 = QPushButton(self.slot_frame)
        self.slot_1.setObjectName(u"slot_1")
        self.slot_1.setGeometry(QRect(130, 20, 115, 210))
        self.slot_2 = QPushButton(self.slot_frame)
        self.slot_2.setObjectName(u"slot_2")
        self.slot_2.setGeometry(QRect(250, 20, 115, 210))
        self.slot_3 = QPushButton(self.slot_frame)
        self.slot_3.setObjectName(u"slot_3")
        self.slot_3.setGeometry(QRect(370, 20, 115, 210))
        self.slot_4 = QPushButton(self.slot_frame)
        self.slot_4.setObjectName(u"slot_4")
        self.slot_4.setGeometry(QRect(490, 20, 115, 210))
        self.slot_6 = QPushButton(self.slot_frame)
        self.slot_6.setObjectName(u"slot_6")
        self.slot_6.setGeometry(QRect(10, 260, 115, 210))
        self.slot_8 = QPushButton(self.slot_frame)
        self.slot_8.setObjectName(u"slot_8")
        self.slot_8.setGeometry(QRect(250, 260, 115, 210))
        self.slot_9 = QPushButton(self.slot_frame)
        self.slot_9.setObjectName(u"slot_9")
        self.slot_9.setGeometry(QRect(370, 260, 115, 210))
        self.slot_7 = QPushButton(self.slot_frame)
        self.slot_7.setObjectName(u"slot_7")
        self.slot_7.setGeometry(QRect(130, 260, 115, 210))
        self.slot_10 = QPushButton(self.slot_frame)
        self.slot_10.setObjectName(u"slot_10")
        self.slot_10.setGeometry(QRect(490, 260, 115, 210))
        self.slot_11 = QPushButton(self.slot_frame)
        self.slot_11.setObjectName(u"slot_11")
        self.slot_11.setGeometry(QRect(610, 260, 115, 210))
        self.slot_5 = QPushButton(self.slot_frame)
        self.slot_5.setObjectName(u"slot_5")
        self.slot_5.setGeometry(QRect(610, 20, 115, 210))
        self.groupBox = QGroupBox(self.tab_3)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(750, 30, 271, 251))
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 30, 111, 211))
        self.layoutWidget1 = QWidget(self.groupBox_2)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(10, 30, 91, 171))
        self.verticalLayout = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.all_opt = QRadioButton(self.layoutWidget1)
        self.all_opt.setObjectName(u"all_opt")

        self.verticalLayout.addWidget(self.all_opt)

        self.available_opt = QRadioButton(self.layoutWidget1)
        self.available_opt.setObjectName(u"available_opt")

        self.verticalLayout.addWidget(self.available_opt)

        self.resersed_opt = QRadioButton(self.layoutWidget1)
        self.resersed_opt.setObjectName(u"resersed_opt")

        self.verticalLayout.addWidget(self.resersed_opt)

        self.unavailable_opt = QRadioButton(self.layoutWidget1)
        self.unavailable_opt.setObjectName(u"unavailable_opt")

        self.verticalLayout.addWidget(self.unavailable_opt)

        self.groupBox_3 = QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(125, 30, 71, 211))
        self.layoutWidget2 = QWidget(self.groupBox_3)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(10, 30, 51, 171))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.layoutWidget2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setStyleSheet(u"background-color: rgb(131, 131, 131);")

        self.verticalLayout_2.addWidget(self.label_3)

        self.label_4 = QLabel(self.layoutWidget2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setStyleSheet(u"background-color: rgb(0, 170, 0);")

        self.verticalLayout_2.addWidget(self.label_4)

        self.label_5 = QLabel(self.layoutWidget2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setStyleSheet(u"background-color: rgb(212, 212, 0);")

        self.verticalLayout_2.addWidget(self.label_5)

        self.label_6 = QLabel(self.layoutWidget2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setStyleSheet(u"background-color: rgb(195, 0, 0);")

        self.verticalLayout_2.addWidget(self.label_6)

        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(200, 30, 61, 211))
        self.layoutWidget3 = QWidget(self.groupBox_4)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(10, 30, 41, 171))
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.all_slot = QLabel(self.layoutWidget3)
        self.all_slot.setObjectName(u"all_slot")

        self.verticalLayout_3.addWidget(self.all_slot)

        self.available_slot = QLabel(self.layoutWidget3)
        self.available_slot.setObjectName(u"available_slot")

        self.verticalLayout_3.addWidget(self.available_slot)

        self.reserved_slot = QLabel(self.layoutWidget3)
        self.reserved_slot.setObjectName(u"reserved_slot")

        self.verticalLayout_3.addWidget(self.reserved_slot)

        self.unavailable_slot = QLabel(self.layoutWidget3)
        self.unavailable_slot.setObjectName(u"unavailable_slot")

        self.verticalLayout_3.addWidget(self.unavailable_slot)

        self.groupBox_5 = QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(750, 290, 271, 141))
        self.layoutWidget4 = QWidget(self.groupBox_5)
        self.layoutWidget4.setObjectName(u"layoutWidget4")
        self.layoutWidget4.setGeometry(QRect(10, 30, 72, 101))
        self.verticalLayout_4 = QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.layoutWidget4)
        self.label_7.setObjectName(u"label_7")

        self.verticalLayout_4.addWidget(self.label_7)

        self.label_10 = QLabel(self.layoutWidget4)
        self.label_10.setObjectName(u"label_10")

        self.verticalLayout_4.addWidget(self.label_10)

        self.label_8 = QLabel(self.layoutWidget4)
        self.label_8.setObjectName(u"label_8")

        self.verticalLayout_4.addWidget(self.label_8)

        self.layoutWidget5 = QWidget(self.groupBox_5)
        self.layoutWidget5.setObjectName(u"layoutWidget5")
        self.layoutWidget5.setGeometry(QRect(90, 30, 171, 101))
        self.verticalLayout_5 = QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.lincense_edit = QLineEdit(self.layoutWidget5)
        self.lincense_edit.setObjectName(u"lincense_edit")
        self.lincense_edit.setReadOnly(True)

        self.verticalLayout_5.addWidget(self.lincense_edit)

        self.type_edit = QLineEdit(self.layoutWidget5)
        self.type_edit.setObjectName(u"type_edit")
        self.type_edit.setReadOnly(True)

        self.verticalLayout_5.addWidget(self.type_edit)

        self.entry_edit = QLineEdit(self.layoutWidget5)
        self.entry_edit.setObjectName(u"entry_edit")
        self.entry_edit.setReadOnly(True)

        self.verticalLayout_5.addWidget(self.entry_edit)

        self.btn_refresh = QPushButton(self.tab_3)
        self.btn_refresh.setObjectName(u"btn_refresh")
        self.btn_refresh.setGeometry(QRect(900, 440, 111, 41))
        self.tabWidget.addTab(self.tab_3, "")
        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(1045, 20, 341, 321))
        self.groupBox_7.setFont(font)
        self.entrance_capture_1 = QLabel(self.groupBox_7)
        self.entrance_capture_1.setObjectName(u"entrance_capture_1")
        self.entrance_capture_1.setGeometry(QRect(10, 20, 320, 150))
        self.entrance_capture_1.setStyleSheet(u"background-color: rgb(109, 109, 109);")
        self.entrance_capture_2 = QLabel(self.groupBox_7)
        self.entrance_capture_2.setObjectName(u"entrance_capture_2")
        self.entrance_capture_2.setGeometry(QRect(10, 175, 320, 100))
        self.entrance_capture_2.setStyleSheet(u"background-color: rgb(109, 109, 109);")
        self.capture_entrance = QPushButton(self.groupBox_7)
        self.capture_entrance.setObjectName(u"capture_entrance")
        self.capture_entrance.setGeometry(QRect(10, 280, 131, 31))
        self.entrance_result = QLineEdit(self.groupBox_7)
        self.entrance_result.setObjectName(u"entrance_result")
        self.entrance_result.setGeometry(QRect(150, 280, 181, 31))
        self.groupBox_8 = QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(1045, 350, 341, 321))
        self.groupBox_8.setFont(font)
        self.exit_capture_1 = QLabel(self.groupBox_8)
        self.exit_capture_1.setObjectName(u"exit_capture_1")
        self.exit_capture_1.setGeometry(QRect(10, 20, 320, 150))
        self.exit_capture_1.setStyleSheet(u"background-color: rgb(109, 109, 109);")
        self.exit_capture_2 = QLabel(self.groupBox_8)
        self.exit_capture_2.setObjectName(u"exit_capture_2")
        self.exit_capture_2.setGeometry(QRect(10, 175, 320, 100))
        self.exit_capture_2.setStyleSheet(u"background-color: rgb(109, 109, 109);")
        self.capture_exit = QPushButton(self.groupBox_8)
        self.capture_exit.setObjectName(u"capture_exit")
        self.capture_exit.setGeometry(QRect(10, 280, 141, 31))
        self.exit_result = QLineEdit(self.groupBox_8)
        self.exit_result.setObjectName(u"exit_result")
        self.exit_result.setGeometry(QRect(160, 280, 171, 31))
        self.groupBox_10 = QGroupBox(self.centralwidget)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(10, 550, 401, 61))
        self.groupBox_10.setFont(font)
        self.layoutWidget6 = QWidget(self.groupBox_10)
        self.layoutWidget6.setObjectName(u"layoutWidget6")
        self.layoutWidget6.setGeometry(QRect(10, 23, 381, 31))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_21 = QLabel(self.layoutWidget6)
        self.label_21.setObjectName(u"label_21")

        self.horizontalLayout_2.addWidget(self.label_21)

        self.btn_connect_cam = QRadioButton(self.layoutWidget6)
        self.btn_connect_cam.setObjectName(u"btn_connect_cam")
        self.btn_connect_cam.setStyleSheet(u"color: rgb(0, 85, 0);")

        self.horizontalLayout_2.addWidget(self.btn_connect_cam)

        self.btn_disconnect_cam = QRadioButton(self.layoutWidget6)
        self.btn_disconnect_cam.setObjectName(u"btn_disconnect_cam")
        self.btn_disconnect_cam.setStyleSheet(u"color: rgb(170, 0, 0);")

        self.horizontalLayout_2.addWidget(self.btn_disconnect_cam)

        self.run_cam = QPushButton(self.layoutWidget6)
        self.run_cam.setObjectName(u"run_cam")

        self.horizontalLayout_2.addWidget(self.run_cam)

        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(1090, 680, 291, 20))
        font1 = QFont()
        font1.setFamilies([u"MS Shell Dlg 2"])
        font1.setPointSize(8)
        font1.setBold(False)
        font1.setItalic(False)
        self.label_18.setFont(font1)
        self.label_18.setStyleSheet(u"font: 8pt \"MS Shell Dlg 2\";")
        self.groupBox_12 = QGroupBox(self.centralwidget)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(570, 540, 301, 141))
        self.groupBox_12.setFont(font)
        self.layoutWidget7 = QWidget(self.groupBox_12)
        self.layoutWidget7.setObjectName(u"layoutWidget7")
        self.layoutWidget7.setGeometry(QRect(10, 30, 281, 111))
        self.formLayout = QFormLayout(self.layoutWidget7)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.label_17 = QLabel(self.layoutWidget7)
        self.label_17.setObjectName(u"label_17")

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.label_17)

        self.lcdNumber = QLCDNumber(self.layoutWidget7)
        self.lcdNumber.setObjectName(u"lcdNumber")

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.lcdNumber)

        self.label_16 = QLabel(self.layoutWidget7)
        self.label_16.setObjectName(u"label_16")

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.label_16)

        self.slot_display = QLineEdit(self.layoutWidget7)
        self.slot_display.setObjectName(u"slot_display")
        self.slot_display.setReadOnly(True)

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.slot_display)

        self.label_19 = QLabel(self.layoutWidget7)
        self.label_19.setObjectName(u"label_19")

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.label_19)

        self.available_slot_display = QLineEdit(self.layoutWidget7)
        self.available_slot_display.setObjectName(u"available_slot_display")
        self.available_slot_display.setReadOnly(True)

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.available_slot_display)

        self.label_20 = QLabel(self.layoutWidget7)
        self.label_20.setObjectName(u"label_20")

        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.label_20)

        self.car_display = QLineEdit(self.layoutWidget7)
        self.car_display.setObjectName(u"car_display")
        self.car_display.setReadOnly(True)

        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.car_display)

        self.groupBox_11 = QGroupBox(self.centralwidget)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(10, 620, 401, 61))
        self.layoutWidget8 = QWidget(self.groupBox_11)
        self.layoutWidget8.setObjectName(u"layoutWidget8")
        self.layoutWidget8.setGeometry(QRect(10, 20, 381, 31))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.port = QComboBox(self.layoutWidget8)
        self.port.addItem("")
        self.port.setObjectName(u"port")

        self.horizontalLayout.addWidget(self.port)

        self.baud = QComboBox(self.layoutWidget8)
        self.baud.addItem("")
        self.baud.addItem("")
        self.baud.addItem("")
        self.baud.addItem("")
        self.baud.addItem("")
        self.baud.addItem("")
        self.baud.addItem("")
        self.baud.addItem("")
        self.baud.addItem("")
        self.baud.addItem("")
        self.baud.setObjectName(u"baud")
        palette = QPalette()
        brush = QBrush(QColor(27, 29, 35, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.baud.setPalette(palette)
        self.baud.setFont(font)
        self.baud.setAutoFillBackground(False)
        self.baud.setStyleSheet(u"")
        self.baud.setIconSize(QSize(16, 16))
        self.baud.setFrame(True)

        self.horizontalLayout.addWidget(self.baud)

        self.btn_connect = QPushButton(self.layoutWidget8)
        self.btn_connect.setObjectName(u"btn_connect")

        self.horizontalLayout.addWidget(self.btn_connect)

        self.groupBox_9 = QGroupBox(self.centralwidget)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(420, 550, 141, 131))
        self.layoutWidget9 = QWidget(self.groupBox_9)
        self.layoutWidget9.setObjectName(u"layoutWidget9")
        self.layoutWidget9.setGeometry(QRect(10, 20, 121, 101))
        self.verticalLayout_8 = QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.btn_send_email = QPushButton(self.layoutWidget9)
        self.btn_send_email.setObjectName(u"btn_send_email")

        self.verticalLayout_8.addWidget(self.btn_send_email)

        self.btn_website = QPushButton(self.layoutWidget9)
        self.btn_website.setObjectName(u"btn_website")
        self.btn_website.setFont(font)

        self.verticalLayout_8.addWidget(self.btn_website)

        self.btn_login = QPushButton(self.layoutWidget9)
        self.btn_login.setObjectName(u"btn_login")
        self.btn_login.setFont(font)

        self.verticalLayout_8.addWidget(self.btn_login)

        self.groupBox_13 = QGroupBox(self.centralwidget)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(880, 540, 161, 61))
        self.style_box = QComboBox(self.groupBox_13)
        self.style_box.setObjectName(u"style_box")
        self.style_box.setGeometry(QRect(10, 20, 141, 31))
        self.groupBox_14 = QGroupBox(self.centralwidget)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setGeometry(QRect(880, 610, 161, 61))
        self.comand_edit = QLineEdit(self.groupBox_14)
        self.comand_edit.setObjectName(u"comand_edit")
        self.comand_edit.setGeometry(QRect(10, 20, 141, 31))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.entrance_view.setText("")
        self.exit_view.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"Entry Camera view", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"License Number", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"username", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Phone", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Slot", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Check-in", None));
        ___qtablewidgetitem5 = self.tableWidget.verticalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"1", None));
        ___qtablewidgetitem6 = self.tableWidget.verticalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"1", None));
        ___qtablewidgetitem7 = self.tableWidget.verticalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"2", None));
        ___qtablewidgetitem8 = self.tableWidget.verticalHeaderItem(3)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"3", None));
        ___qtablewidgetitem9 = self.tableWidget.verticalHeaderItem(4)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"4", None));
        ___qtablewidgetitem10 = self.tableWidget.verticalHeaderItem(5)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"5", None));
        ___qtablewidgetitem11 = self.tableWidget.verticalHeaderItem(6)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"6", None));
        ___qtablewidgetitem12 = self.tableWidget.verticalHeaderItem(7)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"7", None));
        ___qtablewidgetitem13 = self.tableWidget.verticalHeaderItem(8)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"8", None));
        ___qtablewidgetitem14 = self.tableWidget.verticalHeaderItem(9)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"10", None));
        ___qtablewidgetitem15 = self.tableWidget.verticalHeaderItem(10)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"11", None));
        ___qtablewidgetitem16 = self.tableWidget.verticalHeaderItem(11)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"12", None));
        ___qtablewidgetitem17 = self.tableWidget.verticalHeaderItem(12)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"13", None));
        ___qtablewidgetitem18 = self.tableWidget.verticalHeaderItem(13)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"14", None));
        ___qtablewidgetitem19 = self.tableWidget.verticalHeaderItem(14)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"15", None));

        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)

        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Information Filter:", None))
        self.btn_find.setText(QCoreApplication.translate("MainWindow", u"Find", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"From:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"To:", None))
        self.btn_reset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.btn_export.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u" Database View", None))
        self.slot_0.setText(QCoreApplication.translate("MainWindow", u"SA-00", None))
        self.slot_1.setText(QCoreApplication.translate("MainWindow", u"SA-01", None))
        self.slot_2.setText(QCoreApplication.translate("MainWindow", u"SA-02", None))
        self.slot_3.setText(QCoreApplication.translate("MainWindow", u"SA-03", None))
        self.slot_4.setText(QCoreApplication.translate("MainWindow", u"SA-04", None))
        self.slot_6.setText(QCoreApplication.translate("MainWindow", u"SA-06", None))
        self.slot_8.setText(QCoreApplication.translate("MainWindow", u"SA-08", None))
        self.slot_9.setText(QCoreApplication.translate("MainWindow", u"SA-09", None))
        self.slot_7.setText(QCoreApplication.translate("MainWindow", u"SA-07", None))
        self.slot_10.setText(QCoreApplication.translate("MainWindow", u"SA-10", None))
        self.slot_11.setText(QCoreApplication.translate("MainWindow", u"SA-11", None))
        self.slot_5.setText(QCoreApplication.translate("MainWindow", u"SA-05", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Status indiacation:", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"filters", None))
        self.all_opt.setText(QCoreApplication.translate("MainWindow", u"All", None))
        self.available_opt.setText(QCoreApplication.translate("MainWindow", u"Available", None))
        self.resersed_opt.setText(QCoreApplication.translate("MainWindow", u"Reserved", None))
        self.unavailable_opt.setText(QCoreApplication.translate("MainWindow", u"Unvailable", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"color:", None))
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_6.setText("")
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Total:", None))
        self.all_slot.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.available_slot.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.reserved_slot.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.unavailable_slot.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Information:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Plate:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Type:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Entry Time: ", None))
        self.btn_refresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Parking Slot View", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Entrance Capture", None))
        self.entrance_capture_1.setText("")
        self.entrance_capture_2.setText("")
        self.capture_entrance.setText(QCoreApplication.translate("MainWindow", u"Capture Camera", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Exit  Capture", None))
        self.exit_capture_1.setText("")
        self.exit_capture_2.setText("")
        self.capture_exit.setText(QCoreApplication.translate("MainWindow", u"Capture Camera", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Devices Setup:", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Camera:", None))
        self.btn_connect_cam.setText(QCoreApplication.translate("MainWindow", u"Connected", None))
        self.btn_disconnect_cam.setText(QCoreApplication.translate("MainWindow", u"Diconnected", None))
        self.run_cam.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Created by: University of Technology and Education Team", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"Information:", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Current Time:", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Reserved Slot:", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Available Slot:", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Total Car:", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"System Connections:", None))
        self.port.setItemText(0, QCoreApplication.translate("MainWindow", u"Arduino Port", None))

        self.baud.setItemText(0, QCoreApplication.translate("MainWindow", u"Baudrates", None))
        self.baud.setItemText(1, QCoreApplication.translate("MainWindow", u"1200", None))
        self.baud.setItemText(2, QCoreApplication.translate("MainWindow", u"1800", None))
        self.baud.setItemText(3, QCoreApplication.translate("MainWindow", u"2400", None))
        self.baud.setItemText(4, QCoreApplication.translate("MainWindow", u"4800", None))
        self.baud.setItemText(5, QCoreApplication.translate("MainWindow", u"9600", None))
        self.baud.setItemText(6, QCoreApplication.translate("MainWindow", u"38400", None))
        self.baud.setItemText(7, QCoreApplication.translate("MainWindow", u"19200", None))
        self.baud.setItemText(8, QCoreApplication.translate("MainWindow", u"57600", None))
        self.baud.setItemText(9, QCoreApplication.translate("MainWindow", u"115200", None))

        self.btn_connect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Toolkits:", None))
        self.btn_send_email.setText(QCoreApplication.translate("MainWindow", u"Send SMS/Email", None))
        self.btn_website.setText(QCoreApplication.translate("MainWindow", u"Go to Website", None))
        self.btn_login.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"Theme Style:", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("MainWindow", u"Comands:", None))
    # retranslateUi

